services:
  - type: web
    name: disaster-predictor
    env: python
    branch: main
    buildCommand: python -m pip install --no-cache-dir -r requirements.txt
    startCommand: waitress-serve --listen=0.0.0.0:$PORT app:app
    plan: free
